name: Build project and run Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.1
      - name: Setup Sentry CLI
        uses: mathieu-bour/setup-sentry-cli@v1
        with:
          version: latest # optional if 'latest'
          url: https://sentry.io/ # optional if you are using https://sentry.io
          token: ${{ SECRETS.SENTRY_TOKEN }} # from GitHub secrets
          organization: tm-test-rr
          project: javascript-nextjs
      - name: npm install
        run: |
          npm install
      - name: run build
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          NEXT_PUBLIC_BASE_QA_URL: ${{ secrets.NEXT_PUBLIC_BASE_QA_URL }}
          NEXT_PUBLIC_S3_URL: https://d2pyzcqibfhr70.cloudfront.net
          NEXT_PUBLIC_BLUR_DATA_URL: 'data:image/gif;base64, iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mO8UA8AAiUBUcc3qzwAAAAASUVORK5CYII='
          NEXTAUTH_URL: http://localhost:3000
          NEXT_PUBLIC_KAKAO_API_KEY: ${{ secrets.NEXT_PUBLIC_KAKAO_API_KEY }}
          NEXT_PUBLIC_KAKAO_SECRET: ${{ secrets.NEXT_PUBLIC_KAKAO_SECRET }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
      - name: run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npm install -g @lhci/cli@0.8.x
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
